# Generated by Django 4.2.16 on 2024-10-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_id", models.IntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
