# Generated by Django 4.2.16 on 2024-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_username", models.CharField(max_length=150)),
                ("report_file", models.FileField(upload_to="lab_reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
